packages:
  device-manager-service/internal/device/interfaces:
    config:
      recursive: true
      with-expecter: true
    interfaces:
      IDeviceService: 
        output: internal/mocks
      IDeviceRepository:
